function [ROImeans, ROImedians, ROIsums] = LONG_exportROIs(scans_to_process2)
%LONG_extractROIs - export ROI values generated by LONG_extractROIs
%
% Syntax:  [ROImeans, ROImedians] = LONG_exportROIs(scans_to_process2)
%
% Inputs:   scans_to_process - array of objects of class LONG_participant,
%
% Outputs: ROImeans - matrix of mean values (rows = pidn, columns = ROI)
%           ROImedians - matrix of median values (rows = pidn, columns = ROI)
%
% Other m-files required: LONG_participant.m, LONG_setup.m, SPM12b, LONG_extractROIs
% Subfunctions:
%
% MAT-files required: none
% See also: LONG_extractROIs
% To Do: 
%
% Author: Suneth Attygalle
% Created 04/21/2014
%
% Revisions:

for sub = 1:size(scans_to_process2,2)
     ROImeans(sub,:) = scans_to_process2(sub).ROImean(2,:);
     ROImedians(sub,:) = scans_to_process2(sub).ROImedian(2,:);
     ROIsums(sub,:) = scans_to_process2(sub).ROIsum(2,:);
end
ROImeans = [scans_to_process2(1).ROImean(1,:); ROImeans];
PIDNcol = ['PIDN'; {scans_to_process2.PIDN}'];
ROImeans = [PIDNcol, ROImeans ];

ROImedians = [scans_to_process2(1).ROImedian(1,:); ROImedians];
PIDNcol = ['PIDN'; {scans_to_process2.PIDN}'];
ROImedians = [PIDNcol, ROImedians ];

ROIsums = [scans_to_process2(1).ROIsum(1,:); ROIsums];
PIDNcol = ['PIDN'; {scans_to_process2.PIDN}'];
ROIsums = [PIDNcol, ROIsums ];













